# fly.toml app configuration file generated for reflash on 2025-04-08T17:57:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reflash'
primary_region = 'den'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384

[env]
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_KEY = "placeholder-supabase-key"
  OPENAI_API_KEY = "placeholder-openai-key"
