<<<<<<< HEAD
# fly.toml app configuration file generated for reflash on 2025-04-08T15:20:19-06:00
=======
# fly.toml app configuration file generated for reflash on 2025-04-08T21:14:43Z
>>>>>>> 573002f7793ae8b26f379da0fecb670df31b1273
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reflash'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
